// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1.API.Data;

#nullable disable

namespace Parcial1.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230429005152_key")]
    partial class key
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial1.Shared.Entities.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FechaUso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FueUsada")
                        .HasColumnType("bit");

                    b.Property<int>("IdBoleta")
                        .HasColumnType("int");

                    b.Property<string>("Porteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdBoleta")
                        .IsUnique();

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
